version: "3.7"

services:
  drupal:
    build:
      context: .
      dockerfile: .docker/drupal/Dockerfile
      args:
        - GROUP_ID=${GROUP_ID}
        - USER_ID=${USER_ID}
        - DRUPAL_TAG=${DRUPAL_TAG}
        - XDEBUG_VERSION=${XDEBUG_VERSION}
    container_name: "${PROJECT_NAME}_drupal"
    user: ${USER_ID}:${GROUP_ID}
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DRIVER: ${DB_DRIVER}
      DRUPAL_VERSION: ${DRUPAL_VERSION}
      INSTALL_ACCOUNT_NAME: ${INSTALL_ACCOUNT_NAME}
      INSTALL_ACCOUNT_PASS: ${INSTALL_ACCOUNT_PASS}
      INSTALL_ACCOUNT_MAIL: ${INSTALL_ACCOUNT_MAIL}
      DRUSH_OPTIONS_URI: "https://${PROJECT_BASE_URL}"
      ENVIRONMENT: ${ENVIRONMENT}
    volumes:
      - ./project:/home/drupal/project:cached
      - ~/.ssh:/home/drupal/.ssh:ro
    labels:
      - traefik.http.middlewares.${PROJECT_NAME}_drupal_https.redirectscheme.scheme=https
      - traefik.http.routers.${PROJECT_NAME}_drupal.entrypoints=web
      - traefik.http.routers.${PROJECT_NAME}_drupal.rule=Host(`${PROJECT_BASE_URL}`)
      - traefik.http.routers.${PROJECT_NAME}_drupal.middlewares=${PROJECT_NAME}_drupal_https@docker
      - traefik.http.routers.${PROJECT_NAME}_drupal_https.rule=Host(`${PROJECT_BASE_URL}`)
      - traefik.http.routers.${PROJECT_NAME}_drupal_https.tls=true
      - traefik.http.routers.${PROJECT_NAME}_drupal_https.entrypoints=websecure

  db:
    build:
      context: .
      dockerfile: .docker/db/Dockerfile
      args:
        - DB_TAG=${DB_TAG}
        - DB_IMAGE=${DB_IMAGE}
    container_name: "${PROJECT_NAME}_db"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "${DB_HOST}", "-u", "${DB_USER}", "-p${DB_PASSWORD}"]
      timeout: 20s
      interval: 5s
      retries: 10

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: "${PROJECT_NAME}_pma"
    environment:
      PMA_HOST: $DB_HOST
      PMA_USER: $DB_USER
      PMA_PASSWORD: $DB_PASSWORD
      UPLOAD_LIMIT: 1G
    labels:
      - "traefik.http.routers.${PROJECT_NAME}_pma.rule=Host(`pma.${PROJECT_BASE_URL}`)"

  node:
    build:
      context: .
      dockerfile: .docker/node/Dockerfile
      args:
        - NODE_TAG=${NODE_TAG}
        - GROUP_ID=${GROUP_ID}
        - USER_ID=${USER_ID}
    container_name: "${PROJECT_NAME}_node"
    user: ${USER_ID}:${GROUP_ID}
    working_dir: /home/drupal/project/web
    tty: true
    volumes:
    - ./project:/home/drupal/project

  mailhog:
    image: mailhog/mailhog
    container_name: "${PROJECT_NAME}_mailhog"
    labels:
      - "traefik.http.services.${PROJECT_NAME}_mailhog.loadbalancer.server.port=8025"
      - "traefik.http.routers.${PROJECT_NAME}_mailhog.rule=Host(`mailhog.${PROJECT_BASE_URL}`)"

  traefik:
    image: traefik:v2.0
    container_name: "${PROJECT_NAME}_traefik"
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker=true
      - --providers.file.directory=/etc/traefik/dynamic_conf
    ports:
      - '80:80'
      - '443:443'
      # - '8080:8080' # Dashboard
    volumes:
      - ./.docker/traefik/certs:/tools/certs
      - ./.docker/traefik/config.yml:/etc/traefik/dynamic_conf/conf.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock
